---
functional:
  - Незарегистрированный поьзователь может запустить пробную игру
  - На сайте должна быть реализоована регистрация новых пользователей
  - Зарегистрированный пользователь может авторизоваться через электронную почту
  - Пользователь может авторизоваться через GitHub и Discord
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность играть с ботом и другими игроками, видеть код соперника
  - В игре должна быть реализована система рейтингов с доступом игрокам для просмотра, поиска, отслеживания
  - В игре должен быть реализован чат для общения игроков
  - Реализация игры возможность выбрать игры, времени, языка программирования
  - Реализация игры (победа, проиграшь, возможность сдаться, выбор задания, выбор уровня игры
non-functional:
  - безопасность сайта, защита данных польователей
  - сайт должен быть совместим с последними версиями браузеров
  - Интерфейс приложения адаптирован под мобильные устройства
  - Отказоустойчивость сайта (например, 1000 одновременных пользователей)
implicit:
  - Интуитивно понятный интерфейс
  - Реализация интерфейса на русском и английском языках
  - Реализовать защиту от читерства (нельзя копировать код из сторонних источников, копировать код партнера)
