---
functional:
  - Незарегистрированный поьзователь может запустить пробную игру
  - На сайте должна быть реализоована регистрация новых пользователей
  - Зарегистрированный пользователь может авторизоваться через электронную почту
  - Пользователь может авторизоваться через GitHub и Discord
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность игра с ботом и с другими игроками
  - В игре должна быть реализована система рейтингов с доступом игрокам для просмотра, поиска, отслеживания
  - В игре должен быть реализован чат для общения игроков
  - Реализация игры возможность выбрать игры, времени, языка программирования
